### ISSUE TITLE
Card 组件希望提供header 和 footer 的 border相关控制属性和css变量

### ISSUE THREAD

**Issue by NoahSun** [sutras/sard-uniapp#158]
|props|type|default|
|-------|-----|-------|
|border-header|boolean|true|
|border-footer|boolean|true|

|css vars|default|
|-------|-------|
|--sar-card-border-width|1px \| 2rpx|
|--sar-card-border-type|solid|
|--sar-card-border-color|var(--sar-card-border-color)|
|--border-header-border-width|var(--sar-card-border-width)|
|--border-footer-border-width|var(--sar-card-border-width)|
|--border-header-border-type|var(--sar-card-border-type)|
|--border-footer-border-type|var(--sar-card-border-type)|
|--border-header-border-color|var(--sar-card-border-color)|
|--border-footer-border-color|var(--sar-card-border-color)|

```css
// css
.sar-card__header::after{
    border-bottom: var(--border-header-border-width) var(--border-header-border-type) var(--border-header-border-color);
}
.sar-card__footer::before{
    border-top: var(--border-footer-border-width) var(--border-footer-border-type) var(--border-footer-border-color);
}
```

![Image](https://github.com/user-attachments/assets/8e23fcb9-d1f5-4c01-892c-429a6842920a)
