### ISSUE TITLE
微信小程序 tab点击背景

### ISSUE THREAD

**Issue by gaojian123** [sutras/sard-uniapp#37]
您好，我在微信小程序中 tab点击时总是有个背景样式，没有找到对应的css样式设置，这个该如何去掉呢
![image](https://github.com/user-attachments/assets/14de48b3-da93-408e-bff6-590978bce11b)

**Comment by sutras** [comment]
你可以在App.vue文件添加全局样式：
```css
page {
  -webkit-tap-highlight-color: transparent;
}
```
