### ISSUE TITLE
怎么更改主题色啊？

### ISSUE THREAD

**Issue by chergn** [sutras/sard-uniapp#5]
官方库的主色调是蓝色，我们是绿色的。

**Comment by sutras** [comment]
主题色的修改，可以通过覆盖默认的主题色css变量来实现。

在导入sard-uniapp全局样式的后面编写你的覆盖代码，例如：
``` scss
@import "sard-uniapp/index.scss";

page {
  --sar-primary: green;
}
```
